# Generated by Django 5.0.2 on 2024-03-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av_by', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='options',
            field=models.TextField(blank=True, null=True, verbose_name='Опции'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
